"""生成对外产物：iptv.m3u / iptv_all.m3u / iptv_ipv4.m3u / iptv_ipv6.m3u / results.csv

要点：
- 元数据（tvg-id / tvg-name / group-title / tvg-logo / #KODIPROP / #EXTVLCOPT）原样写回；
- 面向播放器的兼容口径：`#EXTM3U` 单独占首行，`#EXTINF` 之后紧跟播放地址（中间只允许
  出现播放必需的 `#EXTVLCOPT` / `#KODIPROP`），分组只写在 `group-title` 里；
  产物以 `text/plain` 下发（见 `main.MEDIA_TYPES`），因为飞牛影视这类按 MIME 判断的
  播放器拿到 `audio/x-mpegurl` 会把它当成「一个视频」去播放而不是解析订阅；
- 原子写入（先 .tmp 再 os.replace），播放器任何时候请求都不会读到半个文件；
- 生成失败不影响上一次的文件。
"""

from __future__ import annotations

import csv
import io
import json
import os
import re
import time
from pathlib import Path
from typing import Any

from . import statuses

_ATTR_ORDER = ("tvg-id", "tvg-name", "tvg-logo", "group-title")

# 跨源择优时用的「同一个频道」判定键：tvg-id 优先，没有才退到频道名。
_WS_RE = re.compile(r"\s+")


def _norm_key(value: Any) -> str:
    return _WS_RE.sub("", str(value or "")).strip().casefold()


def merge_key(row: dict[str, Any]) -> str:
    """这条频道用来和别的源的同名频道配对；返回空串表示不参与合并。"""
    return _norm_key(row.get("tvg_id")) or _norm_key(row.get("name"))


def _speed_rank(row: dict[str, Any]) -> tuple[float, int, float]:
    """择优排序：实测速度 → 成功次数 → 测试耗时（越短越好）。"""
    elapsed = row.get("elapsed_ms")
    return (
        float(row.get("speed_kbps") or 0),
        int(row.get("success_count") or 0),
        -(float(elapsed) if elapsed else 0.0),
    )


def collapse_fastest(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], int]:
    """多源合并后，同一个频道只保留速度最快的一条。

    输入 rows 已按 source_index 排好序，输出保持这个顺序，只是把落选的条目剔除。
    返回 (保留的行, 被合并掉的条数)。落选的条目不进 iptv.m3u，但 iptv_all.m3u 和
    results.csv 里仍然保留，方便回看每个源各自给了什么。
    """
    winners: dict[str, dict[str, Any]] = {}
    for row in rows:
        key = merge_key(row)
        if not key:
            continue
        current = winners.get(key)
        if current is None or _speed_rank(row) > _speed_rank(current):
            winners[key] = row
    kept = [
        row
        for row in rows
        if not merge_key(row) or winners[merge_key(row)] is row
    ]
    return kept, len(rows) - len(kept)



def _esc(value: str) -> str:
    """属性值里的双引号转义，避免破坏 #EXTINF 结构。"""
    return str(value).replace('"', "'").replace("\r", " ").replace("\n", " ")


def render_entry(row: dict[str, Any]) -> str:
    """把一行 channels 记录还原成 #EXTINF + 扩展指令 + URL。"""
    attrs = _json_dict(row.get("attrs"))
    extras = _json_list(row.get("extra_lines"))

    # 数据库列是权威值，覆盖解析时存的属性，保证 Web 端/历史数据一致
    attrs.setdefault("tvg-id", row.get("tvg_id") or "")
    attrs["tvg-name"] = row.get("tvg_name") or row.get("name") or ""
    attrs["tvg-logo"] = row.get("logo") or ""
    attrs["group-title"] = row.get("group_title") or ""

    ordered_keys = [k for k in _ATTR_ORDER if attrs.get(k)] + [
        k for k in attrs if k not in _ATTR_ORDER and attrs.get(k)
    ]
    parts = [f'{key}="{_esc(attrs[key])}"' for key in ordered_keys]
    duration = str(row.get("duration") or "-1")
    name = _esc(row.get("name") or "")
    head = (
        "#EXTINF:%s %s,%s" % (duration, " ".join(parts), name)
        if parts
        else f"#EXTINF:{duration},{name}"
    )

    lines = [head]
    # 只把「播放必需」的扩展行（#EXTVLCOPT 的 UA/Referer、#EXTHTTP、#KODIPROP 的流格式）
    # 留在 #EXTINF 与地址之间；#EXTGRP 无论来自源文件还是我们自己加的都不输出 ——
    # 分组信息已经在 #EXTINF 的 group-title 里（解析时 #EXTGRP 也会被折进这个字段），
    # 而部分播放器（飞牛影视、LunaTV 一类）只把 #EXTINF 紧接的下一行当播放地址，
    # 中间多插一行就把整个频道丢掉了。
    lines.extend(
        e for e in extras
        if isinstance(e, str) and e.startswith("#") and not e.upper().startswith("#EXTGRP")
    )
    lines.append(row["url"])
    return "\n".join(lines)


def build_m3u(rows: list[dict[str, Any]], title: str) -> str:
    out = io.StringIO()
    out.write("#EXTM3U\n")
    out.write(f"# generated by IPTV Auto Tester at {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    out.write(f"# name={title} channels={len(rows)}\n")
    for row in rows:
        out.write(render_entry(row))
        out.write("\n")
    return out.getvalue()


CSV_FIELDS = [
    "频道名称",
    "分组",
    "tvg-id",
    "URL",
    "来自订阅源",
    "协议",
    "IPv4地址",
    "IPv6地址",
    "选用协议族",
    "HTTP状态",
    "最终地址",
    "跳转次数",
    "内容类型",
    "HLS播放列表",
    "分片验证",
    "可播放",
    "连接耗时ms",
    "首包延迟ms",
    "测试耗时ms",
    "速度KB/s",
    "速度MB/s",
    "视频流",
    "音频流",
    "视频编码",
    "音频编码",
    "分辨率",
    "状态",
    "状态说明",
    "失败原因",
    "成功次数",
    "失败次数",
    "连续失败",
    "成功率%",
    "首次出现",
    "最后出现",
    "最后测试",
    "最后成功",
]


def _fmt_ts(value: Any) -> str:
    try:
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(value)))
    except (TypeError, ValueError):
        return ""


def build_csv(rows: list[dict[str, Any]]) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\r\n")
    writer.writerow(CSV_FIELDS)
    for r in rows:
        success = int(r.get("success_count") or 0)
        failure = int(r.get("failure_count") or 0)
        rate = round(success / max(1, success + failure) * 100, 1)
        speed = float(r.get("speed_kbps") or 0)
        writer.writerow(
            [
                r.get("name") or "",
                r.get("group_title") or "",
                r.get("tvg_id") or "",
                r.get("url") or "",
                r.get("source_url") or "",
                r.get("protocol") or "",
                r.get("ipv4_addr") or "",
                r.get("ipv6_addr") or "",
                r.get("family") or "",
                r.get("http_status") or "",
                r.get("final_url") or "",
                r.get("redirect_count") if r.get("redirect_count") is not None else "",
                r.get("content_type") or "",
                statuses.tri_label(r.get("hls_valid")),
                statuses.segment_label(r.get("segment_test")),
                "" if r.get("playable") is None else ("是" if r.get("playable") else "否"),
                round(float(r["connect_ms"]), 1) if r.get("connect_ms") else "",
                round(float(r["latency_ms"]), 1) if r.get("latency_ms") else "",
                round(float(r["elapsed_ms"]), 1) if r.get("elapsed_ms") else "",
                round(speed, 1),
                round(speed / 1024, 2),
                "有" if r.get("has_video") else "",
                "有" if r.get("has_audio") else "",
                r.get("v_codec") or "",
                r.get("a_codec") or "",
                r.get("v_resolution") or "",
                r.get("status") or "",
                statuses.label(r.get("status")),
                r.get("failure_reason") or "",
                success,
                failure,
                int(r.get("consecutive_failures") or 0),
                rate,
                _fmt_ts(r.get("first_seen")),
                _fmt_ts(r.get("last_seen")),
                _fmt_ts(r.get("last_tested_at")),
                _fmt_ts(r.get("last_ok_at")),
            ]
        )
    return buf.getvalue()


def _json_dict(raw: Any) -> dict[str, Any]:
    if isinstance(raw, dict):
        return dict(raw)
    try:
        value = json.loads(raw or "{}")
    except (TypeError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def _json_list(raw: Any) -> list[Any]:
    if isinstance(raw, list):
        return list(raw)
    try:
        value = json.loads(raw or "[]")
    except (TypeError, ValueError):
        return []
    return value if isinstance(value, list) else []


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, path)


def write_outputs(rows_ok: list[dict[str, Any]], rows_all: list[dict[str, Any]], out_dir: Path) -> dict[str, int]:
    """写出全部产物，返回 {文件名: 频道数}。"""
    files: dict[str, int] = {}
    v4 = [r for r in rows_ok if r.get("family") == "ipv4"]
    v6 = [r for r in rows_ok if r.get("family") == "ipv6"]

    targets = {
        "iptv.m3u": build_m3u(rows_ok, "IPTV Auto Tester 可用频道"),
        "iptv_all.m3u": build_m3u(rows_all, "IPTV Auto Tester 全部频道"),
        "iptv_ipv4.m3u": build_m3u(v4, "IPTV Auto Tester IPv4"),
        "iptv_ipv6.m3u": build_m3u(v6, "IPTV Auto Tester IPv6"),
        "results.csv": "\ufeff" + build_csv(rows_all),
    }
    counts = {
        "iptv.m3u": len(rows_ok),
        "iptv_all.m3u": len(rows_all),
        "iptv_ipv4.m3u": len(v4),
        "iptv_ipv6.m3u": len(v6),
        "results.csv": len(rows_all),
    }
    for name, text in targets.items():
        _write(out_dir / name, text)
        files[name] = counts[name]
    return files
